---

- name: install nodejs deps
  sudo: True
  apt: update_cache=yes pkg={{item}} state=present
  with_items:
    - python-software-properties
    - python
    - g++
    - make

- name: Add chris-lea repo
  sudo: True
  apt_repository: repo=ppa:chris-lea/node.js state=present

- name: Install nodejs
  sudo: True
  apt: update_cache=yes pkg=nodejs